name: shopkart_frontend
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.4.1
  shared_preferences: ^0.5.6+3
  provider: ^4.0.4
  http: ^0.12.0+4
  font_awesome_flutter: ^8.8.1
  razorpay_flutter: ^1.1.3
  fluttertoast: ^4.0.1
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: GoogleSans-Medium
      fonts:
        - asset: assets/fonts/GoogleSans-Medium.ttf
    
    - family: GoogleSans-Regular
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
    
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf
